common:
  fp16: true
  log_format: json
  log_interval: 200
  wandb_project: w2v2-cpt-transfer_finetuning

checkpoint:
  save_interval: 10000
  save_interval_updates: 5000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: /workspace/data/manifests/finetune/punjabi
  labels: ltr
  normalize: true

dataset:
  num_workers: 6
  # For debugging on 12 GB 3060
  # max_tokens: 1400000
  # For real runs on 48 GB A6000
  max_tokens: 5600000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 9500
  validate_interval: 10000
  validate_interval_updates: 1000
  train_subset: train-1h
  valid_subset: valid-1h,test-2h

distributed_training:
  ddp_backend: no_c10d
  distributed_world_size: 1

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 13000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.65, 0.25]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.75
  mask_channel_prob: 0.25
  mask_channel_length: 64
  freeze_finetune_updates: 10000
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
