common:
  fp16: true
  log_format: tqdm
  log_interval: 50
  user_dir: /workspace/custom_task
  wandb_project: w2v2-cpt-transfer_pretraining

checkpoint:
  finetune_from_model: /workspace/checkpoints/xlsr2_300m.pt
  # Save every 500 epochs (i.e. never during 10k training updates)
  save_interval: 500
  # Save based on update steps
  save_interval_updates: 2500
  keep_interval_updates: 5
  no_epoch_checkpoints: true

task:
  _name: temp_sampled_audio_pretraining
  sampling_alpha: 0.05
  data: /workspace/data/manifests/pretrain/
  max_sample_size: 240000
  min_sample_size: 16000
  normalize: true

dataset:
  num_workers: 8
  # max_tokens for 40GB A100 GPUs
  max_tokens: 1500000
  skip_invalid_size_inputs_valid_test: true
  # Validate every 500 epochs (i.e. never during 10k training updates)
  validate_interval: 500
  # Validate based on update steps
  validate_interval_updates: 1000
  train_subset: ???
  valid_subset: punjabi_valid

distributed_training:
  ddp_backend: no_c10d

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 10000
  lr: [0.0001]
  update_freq: [32]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 7500

model:
  _name: wav2vec2
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0,0.1,0.999995]
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  conv_bias: true

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16
